//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/19/2024 10:21:50 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Complain.Models
{
    public partial class Form {

        public Form()
        {
            OnCreated();
        }

        public virtual int FromId { get; set; }

        public virtual DateTime? FromData { get; set; }

        public virtual int? ToId { get; set; }

        public virtual int? CCId { get; set; }

        public virtual string FromName { get; set; }

        public virtual string CostomerId { get; set; }

        public virtual DateTime? Lot { get; set; }

        public virtual string ProblemId { get; set; }

        public virtual string ProblemOthet { get; set; }

        public virtual int? Number { get; set; }

        public virtual int? Price { get; set; }

        public virtual string Co { get; set; }

        public virtual int? TypeId { get; set; }

        public virtual string Image { get; set; }

        public virtual string Note { get; set; }

        public virtual int? UserId { get; set; }

        public virtual int? MgId { get; set; }

        public virtual int? StatusId { get; set; }

        public virtual string ImgSignature { get; set; }

        public virtual string ImgSignatureMng { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
