//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/21/2024 4:06:39 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Complain.Models
{
    public partial class VUser {

        public VUser()
        {
            OnCreated();
        }

        public virtual string UserId { get; set; }

        public virtual string Email { get; set; }

        public virtual string DateLogin { get; set; }

        public virtual string RoleId { get; set; }

        public virtual string Password { get; set; }

        public virtual string EmpDepartment { get; set; }

        public virtual string EmpSection { get; set; }

        public virtual string EmpPosition { get; set; }

        public virtual string UserName { get; set; }

        public virtual string RoleName { get; set; }

        public virtual string DepartmentName { get; set; }

        public virtual string SectionName { get; set; }

        public virtual string PositionName { get; set; }

        public virtual string StatusUsId { get; set; }

        public virtual string StatusUSName { get; set; }

        public virtual string ImgProfile { get; set; }

        public virtual string ImgSignature { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
